### ISSUE TITLE
Should we add a CHANGELOG?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/pyo3-async-runtimes#15]
As per title. I think these can be nice user-friendly documents :)

**Comment by cjdsellers** [comment]
This is a good idea, we could just use the same format as the PyO3 `CHANGELOG.md`. 

Should we start from this release though (or add some previous history as well)?

**Comment by davidhewitt** [comment]
Agreed; I like the PyO3 format 😉 

I am happy if we just start from the current version, I think it might be a ton of work to extract history, with diminishing returns.
